name: Publish to npm

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: {}

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Verify package version matches tag
        id: verify
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "Tag: $TAG"
          PKG_VERSION=$(node -p "require('./package.json').version")
          echo "Package version: $PKG_VERSION"
          if [ "$TAG" != "v$PKG_VERSION" ]; then
            echo "Tag does not match package.json version (v$PKG_VERSION). Aborting publish." >&2
            exit 1
          fi

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "Publishing package@$(node -p "require('./package.json').version") to npm..."
          npm publish --access public
